import { Navigation } from '@/types'

export const explore: Navigation = {
  films: {
    title: 'Movies',
    genres: {
      western: 'Western',
      family: 'Family',
      fantasy: 'Fantasy',
      biographical: 'Biographical',
      arthouse: 'Art House',
      action: 'Action',
      military: 'Military',
      detective: 'Detective',
      crime: 'Crime',
      adventures: 'Adventures',
      drama: 'Drama',
      sport: 'Sport',
      fiction: 'Fiction',
      comedy: 'Comedy',
      melodrama: 'Melodrama',
      thriller: 'Thriller',
      horror: 'Horror',
      musical: 'Musical',
      historical: 'Historical',
      documentary: 'Documentary',
      kids: 'Kids',
      travel: 'Travel',
      cognitive: 'Cognitive',
      theatre: 'Theatre',
      concert: 'Concert',
      standup: 'Standup',
      short: 'Short',
      foreign: 'Foreign',
      ukrainian: 'Ukrainian',
      erotic: 'Erotic',
      russian: 'Russian',
    },
    collections: [
      {
        title: 'Netflix',
        url: '/collections/834-filmy-netflix',
      },
      {
        title: 'HBO',
        url: '/collections/1419-filmy-hbo',
      },
      {
        title: 'Amazon Prime',
        url: '/collections/1417-filmy-amazon',
      },
      {
        title: 'Disney+',
        url: '/collections/1075-filmy-disney',
      },
      {
        title: 'Apple TV+',
        url: '/collections/1416-filmy-apple-tv',
      },
    ],
  },
  series: {
    title: 'TV Shows',
    genres: {
      military: 'Military',
      action: 'Action',
      arthouse: 'Art House',
      thriller: 'Thriller',
      horror: 'Horror',
      adventures: 'Adventures',
      family: 'Family',
      fiction: 'Fiction',
      fantasy: 'Fantasy',
      drama: 'Drama',
      melodrama: 'Melodrama',
      sport: 'Sport',
      comedy: 'Comedy',
      detective: 'Detective',
      crime: 'Crime',
      historical: 'Historical',
      biographical: 'Biographical',
      western: 'Western',
      documentary: 'Documentary',
      musical: 'Musical',
      realtv: 'Real TV',
      telecasts: 'Telecast',
      standup: 'Standup',
      foreign: 'Foreign',
      ukrainian: 'Ukrainian',
      erotic: 'Erotic',
      russian: 'Russian',
    },
    collections: [
      {
        title: 'Netflix',
        url: '/collections/640-serialy-netflix',
      },
      {
        title: 'HBO',
        url: '/collections/639-serialy-hbo',
      },
      {
        title: 'Amazon Prime',
        url: '/collections/831-serialy-amazon',
      },
      {
        title: 'Disney+',
        url: '/collections/1148-serialy-disney',
      },
      {
        title: 'Apple TV+',
        url: '/collections/1146-serialy-apple-tv',
      },
      {
        title: 'Hulu',
        url: '/collections/813-serialy-hulu',
      },
      {
        title: 'Epix',
        url: '/collections/1251-serialy-epix',
      },
    ],
  },
  cartoons: {
    title: 'Cartoons',
    genres: {
      fiction: 'Fiction',
      fantasy: 'Fantasy',
      action: 'Action',
      biographical: 'Biographical',
      comedy: 'Comedy',
      western: 'Western',
      military: 'Military',
      drama: 'Drama',
      melodrama: 'Melodrama',
      arthouse: 'Art House',
      detective: 'Detective',
      crime: 'Crime',
      thriller: 'Thriller',
      historical: 'Historical',
      documentary: 'Documentary',
      fairytale: 'Fairytale',
      family: 'Family',
      horror: 'Horror',
      adventures: 'Adventures',
      sport: 'Sport',
      cognitive: 'Cognitive',
      musical: 'Musical',
      anime: 'Anime',
      kids: 'Kids',
      multseries: 'Cartoon Series',
      short: 'Short',
      'full-length': 'Full-length',
      foreign: 'Foreign',
      ukrainian: 'Ukrainian',
      russian: 'Russian',
      soyzmyltfilm: 'USSR Multfilm',
      adult: 'Adult',
      erotic: 'Erotic',
    },
    collections: [
      {
        title: 'Netflix',
        url: '/collections/1004-animacionnye-serialy-netflix',
      },
      {
        title: 'Disney+',
        url: '/collections/1-multfilmy-disney',
      },
    ],
  },
  animation: {
    title: 'Anime',
    genres: {
      military: 'Military',
      drama: 'Drama',
      detective: 'Detective',
      thriller: 'Thriller',
      comedy: 'Comedy',
      fiction: 'Fiction',
      fantasy: 'Fantasy',
      adventures: 'Adventures',
      romance: 'Romance',
      historical: 'Historical',
      horror: 'Horror',
      mystery: 'Mystery',
      musical: 'Musical',
      action: 'Action',
      fighting: 'Fighting',
      samurai: 'Samurai',
      sport: 'Sport',
      educational: 'Educational',
      everyday: 'Everyday',
      parody: 'Parody',
      school: 'School',
      kids: 'Kids',
      fairytale: 'Fairytale',
      kodomo: 'Kodomo',
      shoujoai: 'Shoujo-ai',
      shoujo: 'Shoujo',
      shounen: 'Shounen',
      shounenai: 'Shounen-ai',
      mahoushoujo: 'Mahou-shoujo',
      mecha: 'Меха',
      ecchi: 'Этти',
      erotic: 'Erotic',
    },
    collections: [
      {
        title: 'Netflix',
        url: '/collections/1242-anime-netflix',
      },
    ],
  },
}
