import { Navigation } from '@/types'

export const explore: Navigation = {
  films: {
    title: 'Фильмы',
    genres: {
      western: 'Вестерны',
      family: 'Семейные',
      fantasy: 'Фэнтези',
      biographical: 'Биографические',
      arthouse: 'Арт-хаус',
      action: 'Боевики',
      military: 'Военные',
      detective: 'Детективы',
      crime: 'Криминал',
      adventures: 'Приключения',
      drama: 'Драмы',
      sport: 'Спортивные',
      fiction: 'Фантастика',
      comedy: 'Комедии',
      melodrama: 'Мелодрамы',
      thriller: 'Триллеры',
      horror: 'Ужасы',
      musical: 'Музыкальные',
      historical: 'Исторические',
      documentary: 'Документальные',
      erotic: 'Эротика',
      kids: 'Детские',
      travel: 'Путешествия',
      cognitive: 'Познавательные',
      theatre: 'Театр',
      concert: 'Концерт',
      standup: 'Стендап',
      short: 'Короткометражные',
      russian: 'Русские',
      ukrainian: 'Украинские',
      foreign: 'Зарубежные',
    },
    collections: [
      {
        title: 'Фильмы Netflix',
        url: '/collections/834-filmy-netflix/',
      },
      {
        title: 'Фильмы HBO и HBO Max',
        url: '/collections/1419-filmy-hbo/',
      },
      {
        title: 'Фильмы Amazon',
        url: '/collections/1417-filmy-amazon/',
      },
      {
        title: 'Фильмы Disney',
        url: '/collections/1075-filmy-disney/',
      },
      {
        title: 'Фильмы Apple TV+',
        url: '/collections/1416-filmy-apple-tv/',
      },
    ],
  },
  series: {
    title: 'Сериалы',
    genres: {
      military: 'Военные',
      action: 'Боевики',
      arthouse: 'Арт-хаус',
      thriller: 'Триллеры',
      horror: 'Ужасы',
      adventures: 'Приключения',
      family: 'Семейные',
      fiction: 'Фантастика',
      fantasy: 'Фэнтези',
      drama: 'Драмы',
      melodrama: 'Мелодрамы',
      sport: 'Спортивные',
      comedy: 'Комедии',
      detective: 'Детективы',
      crime: 'Криминал',
      historical: 'Исторические',
      biographical: 'Биографические',
      western: 'Вестерны',
      documentary: 'Документальные',
      musical: 'Музыкальные',
      realtv: 'Реальное ТВ',
      telecasts: 'Телепередачи',
      standup: 'Стендап',
      erotic: 'Эротика',
      russian: 'Русские',
      ukrainian: 'Украинские',
      foreign: 'Зарубежные',
    },
    collections: [
      {
        title: 'Сериалы Netflix',
        url: '/collections/640-serialy-netflix/',
      },
      {
        title: 'Сериалы HBO и HBO Max',
        url: '/collections/639-serialy-hbo/',
      },
      {
        title: 'Сериалы Amazon Prime',
        url: '/collections/831-serialy-amazon/',
      },
      {
        title: 'Сериалы Disney+',
        url: '/collections/1148-serialy-disney/',
      },
      {
        title: 'Сериалы Apple TV+',
        url: '/collections/1146-serialy-apple-tv/',
      },
      {
        title: 'Сериалы Hulu',
        url: '/collections/813-serialy-hulu/',
      },
      {
        title: 'Сериалы Epix',
        url: '/collections/1251-serialy-epix/',
      },
    ],
  },
  cartoons: {
    title: 'Мультфильмы',
    genres: {
      fiction: 'Фантастика',
      fantasy: 'Фэнтези',
      action: 'Боевики',
      biographical: 'Биографические',
      comedy: 'Комедии',
      western: 'Вестерны',
      military: 'Военные',
      drama: 'Драмы',
      melodrama: 'Мелодрамы',
      arthouse: 'Арт-хаус',
      detective: 'Детективы',
      crime: 'Криминал',
      thriller: 'Триллеры',
      historical: 'Исторические',
      documentary: 'Документальные',
      erotic: 'Эротика',
      fairytale: 'Сказки',
      family: 'Семейные',
      horror: 'Ужасы',
      adventures: 'Приключения',
      sport: 'Спортивные',
      cognitive: 'Познавательные',
      musical: 'Мюзиклы',
      anime: 'Аниме',
      kids: 'Детские',
      adult: 'Для взрослых',
      multseries: 'Мультсериалы',
      short: 'Короткометражные',
      'full-length': 'Полнометражные',
      soyzmyltfilm: 'Советские',
      russian: 'Русские',
      ukrainian: 'Украинские',
      foreign: 'Зарубежные',
    },
    collections: [
      {
        title: 'Мультфильмы Netflix',
        url: '/collections/1004-animacionnye-serialy-netflix/',
      },
      {
        title: 'Мультфильмы Disney',
        url: '/collections/1-multfilmy-disney/',
      },
    ],
  },
  animation: {
    title: 'Аниме',
    genres: {
      military: 'Военные',
      drama: 'Драмы',
      detective: 'Детективы',
      thriller: 'Триллеры',
      comedy: 'Комедии',
      fiction: 'Фантастика',
      fantasy: 'Фэнтези',
      adventures: 'Приключения',
      romance: 'Романтические',
      historical: 'Исторические',
      horror: 'Ужасы',
      mystery: 'Мистические',
      musical: 'Музыкальные',
      erotic: 'Эротика',
      action: 'Боевики',
      fighting: 'Боевые искусства',
      samurai: 'Самурайский боевик',
      sport: 'Спортивные',
      educational: 'Образовательные',
      everyday: 'Повседневность',
      parody: 'Пародия',
      school: 'Школа',
      kids: 'Детские',
      fairytale: 'Сказки',
      kodomo: 'Кодомо',
      shoujoai: 'Сёдзё-ай',
      shoujo: 'Сёдзё',
      shounen: 'Сёнэн',
      shounenai: 'Сёнэн-ай',
      ecchi: 'Этти',
      mahoushoujo: 'Махо-сёдзё',
      mecha: 'Меха',
    },
    collections: [
      {
        title: 'Аниме Netflix',
        url: '/collections/1242-anime-netflix/',
      },
    ],
  },
}
